version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=transactiondb
      - MYSQL_USER=aspuser2
      - MYSQL_PASSWORD=AspUser1&10
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
  app:
    build: .
    depends_on:
      - mysqldb
    restart: on-failure
    env_file: ./.env
    ports:
      - 444:443
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: